// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/avro/options.proto

package avropb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AvroFieldOptions allows specifying Avro-specific metadata on proto fields.
// This is used to generate Avro logicalType annotations (e.g. decimal).
type AvroFieldOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Avro logicalType (e.g. "decimal", "timestamp-millis")
	LogicalType string `protobuf:"bytes,1,opt,name=logical_type,json=logicalType,proto3" json:"logical_type,omitempty"`
	// Precision for decimal logicalType
	Precision int32 `protobuf:"varint,2,opt,name=precision,proto3" json:"precision,omitempty"`
	// Scale for decimal logicalType
	Scale int32 `protobuf:"varint,3,opt,name=scale,proto3" json:"scale,omitempty"`
	// Size in bytes for Avro fixed type
	FixedSize int32 `protobuf:"varint,4,opt,name=fixed_size,json=fixedSize,proto3" json:"fixed_size,omitempty"`
	// Explicit name for the Avro fixed type.
	// If omitted, a deterministic name is auto-generated (e.g. "Decimal38_9").
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	// Override the Avro field name.
	// If omitted, the Proto field name is used.
	FieldName     string `protobuf:"bytes,6,opt,name=field_name,json=fieldName,proto3" json:"field_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvroFieldOptions) Reset() {
	*x = AvroFieldOptions{}
	mi := &file_proto_avro_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvroFieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvroFieldOptions) ProtoMessage() {}

func (x *AvroFieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_avro_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvroFieldOptions.ProtoReflect.Descriptor instead.
func (*AvroFieldOptions) Descriptor() ([]byte, []int) {
	return file_proto_avro_options_proto_rawDescGZIP(), []int{0}
}

func (x *AvroFieldOptions) GetLogicalType() string {
	if x != nil {
		return x.LogicalType
	}
	return ""
}

func (x *AvroFieldOptions) GetPrecision() int32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *AvroFieldOptions) GetScale() int32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *AvroFieldOptions) GetFixedSize() int32 {
	if x != nil {
		return x.FixedSize
	}
	return 0
}

func (x *AvroFieldOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AvroFieldOptions) GetFieldName() string {
	if x != nil {
		return x.FieldName
	}
	return ""
}

// AvroFileOptions allows specifying Avro-specific metadata at file level.
type AvroFileOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Avro namespace for top-level records in this file.
	// Overrides the namespace_map plugin parameter for this file.
	Namespace     string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvroFileOptions) Reset() {
	*x = AvroFileOptions{}
	mi := &file_proto_avro_options_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvroFileOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvroFileOptions) ProtoMessage() {}

func (x *AvroFileOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_avro_options_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvroFileOptions.ProtoReflect.Descriptor instead.
func (*AvroFileOptions) Descriptor() ([]byte, []int) {
	return file_proto_avro_options_proto_rawDescGZIP(), []int{1}
}

func (x *AvroFileOptions) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

// AvroMessageOptions allows specifying Avro-specific metadata at message level.
type AvroMessageOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Override the Avro record name.
	// If omitted, the Proto message name is used.
	// Useful when the Proto message name must differ from the desired Avro record name
	// (e.g. to avoid name collisions within the same Proto package).
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvroMessageOptions) Reset() {
	*x = AvroMessageOptions{}
	mi := &file_proto_avro_options_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvroMessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvroMessageOptions) ProtoMessage() {}

func (x *AvroMessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_proto_avro_options_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvroMessageOptions.ProtoReflect.Descriptor instead.
func (*AvroMessageOptions) Descriptor() ([]byte, []int) {
	return file_proto_avro_options_proto_rawDescGZIP(), []int{2}
}

func (x *AvroMessageOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var file_proto_avro_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*AvroFieldOptions)(nil),
		Field:         50001,
		Name:          "avro.avro",
		Tag:           "bytes,50001,opt,name=avro",
		Filename:      "proto/avro/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: (*AvroFileOptions)(nil),
		Field:         50002,
		Name:          "avro.avro_file",
		Tag:           "bytes,50002,opt,name=avro_file",
		Filename:      "proto/avro/options.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*AvroMessageOptions)(nil),
		Field:         50003,
		Name:          "avro.avro_message",
		Tag:           "bytes,50003,opt,name=avro_message",
		Filename:      "proto/avro/options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional avro.AvroFieldOptions avro = 50001;
	E_Avro = &file_proto_avro_options_proto_extTypes[0]
)

// Extension fields to descriptorpb.FileOptions.
var (
	// optional avro.AvroFileOptions avro_file = 50002;
	E_AvroFile = &file_proto_avro_options_proto_extTypes[1]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional avro.AvroMessageOptions avro_message = 50003;
	E_AvroMessage = &file_proto_avro_options_proto_extTypes[2]
)

var File_proto_avro_options_proto protoreflect.FileDescriptor

const file_proto_avro_options_proto_rawDesc = "" +
	"\n" +
	"\x18proto/avro/options.proto\x12\x04avro\x1a google/protobuf/descriptor.proto\"\xbb\x01\n" +
	"\x10AvroFieldOptions\x12!\n" +
	"\flogical_type\x18\x01 \x01(\tR\vlogicalType\x12\x1c\n" +
	"\tprecision\x18\x02 \x01(\x05R\tprecision\x12\x14\n" +
	"\x05scale\x18\x03 \x01(\x05R\x05scale\x12\x1d\n" +
	"\n" +
	"fixed_size\x18\x04 \x01(\x05R\tfixedSize\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"field_name\x18\x06 \x01(\tR\tfieldName\"/\n" +
	"\x0fAvroFileOptions\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\"(\n" +
	"\x12AvroMessageOptions\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name:K\n" +
	"\x04avro\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\v2\x16.avro.AvroFieldOptionsR\x04avro:R\n" +
	"\tavro_file\x12\x1c.google.protobuf.FileOptions\x18҆\x03 \x01(\v2\x15.avro.AvroFileOptionsR\bavroFile:^\n" +
	"\favro_message\x12\x1f.google.protobuf.MessageOptions\x18ӆ\x03 \x01(\v2\x18.avro.AvroMessageOptionsR\vavroMessageB1Z/github.com/ajainc/protoc-gen-avro/avropb;avropbb\x06proto3"

var (
	file_proto_avro_options_proto_rawDescOnce sync.Once
	file_proto_avro_options_proto_rawDescData []byte
)

func file_proto_avro_options_proto_rawDescGZIP() []byte {
	file_proto_avro_options_proto_rawDescOnce.Do(func() {
		file_proto_avro_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_avro_options_proto_rawDesc), len(file_proto_avro_options_proto_rawDesc)))
	})
	return file_proto_avro_options_proto_rawDescData
}

var file_proto_avro_options_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_avro_options_proto_goTypes = []any{
	(*AvroFieldOptions)(nil),            // 0: avro.AvroFieldOptions
	(*AvroFileOptions)(nil),             // 1: avro.AvroFileOptions
	(*AvroMessageOptions)(nil),          // 2: avro.AvroMessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 3: google.protobuf.FieldOptions
	(*descriptorpb.FileOptions)(nil),    // 4: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil), // 5: google.protobuf.MessageOptions
}
var file_proto_avro_options_proto_depIdxs = []int32{
	3, // 0: avro.avro:extendee -> google.protobuf.FieldOptions
	4, // 1: avro.avro_file:extendee -> google.protobuf.FileOptions
	5, // 2: avro.avro_message:extendee -> google.protobuf.MessageOptions
	0, // 3: avro.avro:type_name -> avro.AvroFieldOptions
	1, // 4: avro.avro_file:type_name -> avro.AvroFileOptions
	2, // 5: avro.avro_message:type_name -> avro.AvroMessageOptions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	3, // [3:6] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_avro_options_proto_init() }
func file_proto_avro_options_proto_init() {
	if File_proto_avro_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_avro_options_proto_rawDesc), len(file_proto_avro_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_proto_avro_options_proto_goTypes,
		DependencyIndexes: file_proto_avro_options_proto_depIdxs,
		MessageInfos:      file_proto_avro_options_proto_msgTypes,
		ExtensionInfos:    file_proto_avro_options_proto_extTypes,
	}.Build()
	File_proto_avro_options_proto = out.File
	file_proto_avro_options_proto_goTypes = nil
	file_proto_avro_options_proto_depIdxs = nil
}
