// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: avro/options.proto

package avropb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AvroFieldOptions allows specifying Avro-specific metadata on proto fields.
// This is used to generate Avro logicalType annotations (e.g. decimal).
type AvroFieldOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Avro logicalType (e.g. "decimal", "timestamp-millis")
	LogicalType string `protobuf:"bytes,1,opt,name=logical_type,json=logicalType,proto3" json:"logical_type,omitempty"`
	// Precision for decimal logicalType
	Precision int32 `protobuf:"varint,2,opt,name=precision,proto3" json:"precision,omitempty"`
	// Scale for decimal logicalType
	Scale int32 `protobuf:"varint,3,opt,name=scale,proto3" json:"scale,omitempty"`
	// Size in bytes for Avro fixed type
	FixedSize     int32 `protobuf:"varint,4,opt,name=fixed_size,json=fixedSize,proto3" json:"fixed_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AvroFieldOptions) Reset() {
	*x = AvroFieldOptions{}
	mi := &file_avro_options_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AvroFieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AvroFieldOptions) ProtoMessage() {}

func (x *AvroFieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_avro_options_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AvroFieldOptions.ProtoReflect.Descriptor instead.
func (*AvroFieldOptions) Descriptor() ([]byte, []int) {
	return file_avro_options_proto_rawDescGZIP(), []int{0}
}

func (x *AvroFieldOptions) GetLogicalType() string {
	if x != nil {
		return x.LogicalType
	}
	return ""
}

func (x *AvroFieldOptions) GetPrecision() int32 {
	if x != nil {
		return x.Precision
	}
	return 0
}

func (x *AvroFieldOptions) GetScale() int32 {
	if x != nil {
		return x.Scale
	}
	return 0
}

func (x *AvroFieldOptions) GetFixedSize() int32 {
	if x != nil {
		return x.FixedSize
	}
	return 0
}

var file_avro_options_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*AvroFieldOptions)(nil),
		Field:         50001,
		Name:          "avro.avro",
		Tag:           "bytes,50001,opt,name=avro",
		Filename:      "avro/options.proto",
	},
}

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional avro.AvroFieldOptions avro = 50001;
	E_Avro = &file_avro_options_proto_extTypes[0]
)

var File_avro_options_proto protoreflect.FileDescriptor

const file_avro_options_proto_rawDesc = "" +
	"\n" +
	"\x12avro/options.proto\x12\x04avro\x1a google/protobuf/descriptor.proto\"\x88\x01\n" +
	"\x10AvroFieldOptions\x12!\n" +
	"\flogical_type\x18\x01 \x01(\tR\vlogicalType\x12\x1c\n" +
	"\tprecision\x18\x02 \x01(\x05R\tprecision\x12\x14\n" +
	"\x05scale\x18\x03 \x01(\x05R\x05scale\x12\x1d\n" +
	"\n" +
	"fixed_size\x18\x04 \x01(\x05R\tfixedSize:K\n" +
	"\x04avro\x12\x1d.google.protobuf.FieldOptions\x18ц\x03 \x01(\v2\x16.avro.AvroFieldOptionsR\x04avroB1Z/github.com/ajainc/protoc-gen-avro/avropb;avropbb\x06proto3"

var (
	file_avro_options_proto_rawDescOnce sync.Once
	file_avro_options_proto_rawDescData []byte
)

func file_avro_options_proto_rawDescGZIP() []byte {
	file_avro_options_proto_rawDescOnce.Do(func() {
		file_avro_options_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_avro_options_proto_rawDesc), len(file_avro_options_proto_rawDesc)))
	})
	return file_avro_options_proto_rawDescData
}

var file_avro_options_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_avro_options_proto_goTypes = []any{
	(*AvroFieldOptions)(nil),          // 0: avro.AvroFieldOptions
	(*descriptorpb.FieldOptions)(nil), // 1: google.protobuf.FieldOptions
}
var file_avro_options_proto_depIdxs = []int32{
	1, // 0: avro.avro:extendee -> google.protobuf.FieldOptions
	0, // 1: avro.avro:type_name -> avro.AvroFieldOptions
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	1, // [1:2] is the sub-list for extension type_name
	0, // [0:1] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_avro_options_proto_init() }
func file_avro_options_proto_init() {
	if File_avro_options_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_avro_options_proto_rawDesc), len(file_avro_options_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_avro_options_proto_goTypes,
		DependencyIndexes: file_avro_options_proto_depIdxs,
		MessageInfos:      file_avro_options_proto_msgTypes,
		ExtensionInfos:    file_avro_options_proto_extTypes,
	}.Build()
	File_avro_options_proto = out.File
	file_avro_options_proto_goTypes = nil
	file_avro_options_proto_depIdxs = nil
}
